// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.5
// source: data_service.proto

package data_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NWPCDataService_FindDataPath_FullMethodName     = "/NWPCDataService/FindDataPath"
	NWPCDataService_GetDataFileInfo_FullMethodName  = "/NWPCDataService/GetDataFileInfo"
	NWPCDataService_DownloadDataFile_FullMethodName = "/NWPCDataService/DownloadDataFile"
)

// NWPCDataServiceClient is the client API for NWPCDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NWPCDataServiceClient interface {
	FindDataPath(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataPathResponse, error)
	GetDataFileInfo(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataFileResponse, error)
	DownloadDataFile(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (NWPCDataService_DownloadDataFileClient, error)
}

type nWPCDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNWPCDataServiceClient(cc grpc.ClientConnInterface) NWPCDataServiceClient {
	return &nWPCDataServiceClient{cc}
}

func (c *nWPCDataServiceClient) FindDataPath(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataPathResponse, error) {
	out := new(DataPathResponse)
	err := c.cc.Invoke(ctx, NWPCDataService_FindDataPath_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nWPCDataServiceClient) GetDataFileInfo(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataFileResponse, error) {
	out := new(DataFileResponse)
	err := c.cc.Invoke(ctx, NWPCDataService_GetDataFileInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nWPCDataServiceClient) DownloadDataFile(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (NWPCDataService_DownloadDataFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &NWPCDataService_ServiceDesc.Streams[0], NWPCDataService_DownloadDataFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &nWPCDataServiceDownloadDataFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NWPCDataService_DownloadDataFileClient interface {
	Recv() (*FileContentResponse, error)
	grpc.ClientStream
}

type nWPCDataServiceDownloadDataFileClient struct {
	grpc.ClientStream
}

func (x *nWPCDataServiceDownloadDataFileClient) Recv() (*FileContentResponse, error) {
	m := new(FileContentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NWPCDataServiceServer is the server API for NWPCDataService service.
// All implementations must embed UnimplementedNWPCDataServiceServer
// for forward compatibility
type NWPCDataServiceServer interface {
	FindDataPath(context.Context, *DataRequest) (*DataPathResponse, error)
	GetDataFileInfo(context.Context, *DataRequest) (*DataFileResponse, error)
	DownloadDataFile(*DataRequest, NWPCDataService_DownloadDataFileServer) error
	mustEmbedUnimplementedNWPCDataServiceServer()
}

// UnimplementedNWPCDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNWPCDataServiceServer struct {
}

func (UnimplementedNWPCDataServiceServer) FindDataPath(context.Context, *DataRequest) (*DataPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDataPath not implemented")
}
func (UnimplementedNWPCDataServiceServer) GetDataFileInfo(context.Context, *DataRequest) (*DataFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataFileInfo not implemented")
}
func (UnimplementedNWPCDataServiceServer) DownloadDataFile(*DataRequest, NWPCDataService_DownloadDataFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadDataFile not implemented")
}
func (UnimplementedNWPCDataServiceServer) mustEmbedUnimplementedNWPCDataServiceServer() {}

// UnsafeNWPCDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NWPCDataServiceServer will
// result in compilation errors.
type UnsafeNWPCDataServiceServer interface {
	mustEmbedUnimplementedNWPCDataServiceServer()
}

func RegisterNWPCDataServiceServer(s grpc.ServiceRegistrar, srv NWPCDataServiceServer) {
	s.RegisterService(&NWPCDataService_ServiceDesc, srv)
}

func _NWPCDataService_FindDataPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NWPCDataServiceServer).FindDataPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NWPCDataService_FindDataPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NWPCDataServiceServer).FindDataPath(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NWPCDataService_GetDataFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NWPCDataServiceServer).GetDataFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NWPCDataService_GetDataFileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NWPCDataServiceServer).GetDataFileInfo(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NWPCDataService_DownloadDataFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NWPCDataServiceServer).DownloadDataFile(m, &nWPCDataServiceDownloadDataFileServer{stream})
}

type NWPCDataService_DownloadDataFileServer interface {
	Send(*FileContentResponse) error
	grpc.ServerStream
}

type nWPCDataServiceDownloadDataFileServer struct {
	grpc.ServerStream
}

func (x *nWPCDataServiceDownloadDataFileServer) Send(m *FileContentResponse) error {
	return x.ServerStream.SendMsg(m)
}

// NWPCDataService_ServiceDesc is the grpc.ServiceDesc for NWPCDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NWPCDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NWPCDataService",
	HandlerType: (*NWPCDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindDataPath",
			Handler:    _NWPCDataService_FindDataPath_Handler,
		},
		{
			MethodName: "GetDataFileInfo",
			Handler:    _NWPCDataService_GetDataFileInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadDataFile",
			Handler:       _NWPCDataService_DownloadDataFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data_service.proto",
}
