// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data_service.proto

package data_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataRequest struct {
	DataType             string   `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	StartTime            string   `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ForecastTime         string   `protobuf:"bytes,3,opt,name=forecast_time,json=forecastTime,proto3" json:"forecast_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{0}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *DataRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *DataRequest) GetForecastTime() string {
	if m != nil {
		return m.ForecastTime
	}
	return ""
}

type DataPathResponse struct {
	LocationType         string   `protobuf:"bytes,1,opt,name=location_type,json=locationType,proto3" json:"location_type,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataPathResponse) Reset()         { *m = DataPathResponse{} }
func (m *DataPathResponse) String() string { return proto.CompactTextString(m) }
func (*DataPathResponse) ProtoMessage()    {}
func (*DataPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{1}
}

func (m *DataPathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataPathResponse.Unmarshal(m, b)
}
func (m *DataPathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataPathResponse.Marshal(b, m, deterministic)
}
func (m *DataPathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPathResponse.Merge(m, src)
}
func (m *DataPathResponse) XXX_Size() int {
	return xxx_messageInfo_DataPathResponse.Size(m)
}
func (m *DataPathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataPathResponse proto.InternalMessageInfo

func (m *DataPathResponse) GetLocationType() string {
	if m != nil {
		return m.LocationType
	}
	return ""
}

func (m *DataPathResponse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func init() {
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*DataPathResponse)(nil), "DataPathResponse")
}

func init() { proto.RegisterFile("data_service.proto", fileDescriptor_3385cd32ad6cfe64) }

var fileDescriptor_3385cd32ad6cfe64 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x7d, 0x0a, 0xf2, 0x3a, 0x46, 0xd4, 0xac, 0x4a, 0x45, 0x90, 0xba, 0x71, 0x55, 0x50,
	0x3f, 0xc1, 0xe2, 0x52, 0x4a, 0x5b, 0x70, 0x59, 0xc6, 0x76, 0xc4, 0x80, 0x4d, 0x62, 0x32, 0x0a,
	0xfd, 0x7b, 0x49, 0x6c, 0xa4, 0xb8, 0x9c, 0x9b, 0x93, 0x9c, 0xdc, 0x01, 0x39, 0x21, 0xe3, 0xe0,
	0xc9, 0x7d, 0xab, 0x91, 0x2a, 0xeb, 0x0c, 0x9b, 0x52, 0xc3, 0x49, 0x8d, 0x8c, 0x2d, 0x7d, 0x7e,
	0x91, 0x67, 0x79, 0x09, 0x59, 0x84, 0x78, 0xb1, 0x94, 0xef, 0xae, 0x77, 0xb7, 0x59, 0xbb, 0x0f,
	0x41, 0xbf, 0x58, 0x92, 0x57, 0x00, 0x9e, 0xd1, 0xf1, 0xc0, 0x6a, 0xa6, 0xfc, 0x30, 0x9e, 0x66,
	0x31, 0xe9, 0xd5, 0x4c, 0xf2, 0x06, 0x4e, 0xdf, 0x8c, 0xa3, 0x11, 0xfd, 0x4a, 0x1c, 0x45, 0x42,
	0xa4, 0x30, 0x40, 0x65, 0x07, 0xe7, 0xc1, 0xd7, 0x20, 0xbf, 0xb7, 0xe4, 0xad, 0xd1, 0x3e, 0x5e,
	0xfc, 0x30, 0x23, 0xb2, 0x32, 0x7a, 0x2b, 0x16, 0x29, 0x8c, 0xf2, 0x02, 0xf6, 0x69, 0x5e, 0xd5,
	0x7f, 0xf3, 0x7d, 0x0d, 0x67, 0xcf, 0x2f, 0xcd, 0x63, 0x78, 0xb8, 0xfb, 0x6d, 0x27, 0xef, 0x40,
	0x3c, 0x29, 0x3d, 0x25, 0x97, 0x14, 0xd5, 0xa6, 0x66, 0x71, 0x51, 0xfd, 0xff, 0x44, 0x79, 0xf0,
	0x7a, 0x1c, 0x37, 0xf2, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x30, 0x6d, 0xb9, 0x48, 0x27, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NWPCDataServiceClient is the client API for NWPCDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NWPCDataServiceClient interface {
	FindDataPath(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataPathResponse, error)
}

type nWPCDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewNWPCDataServiceClient(cc *grpc.ClientConn) NWPCDataServiceClient {
	return &nWPCDataServiceClient{cc}
}

func (c *nWPCDataServiceClient) FindDataPath(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataPathResponse, error) {
	out := new(DataPathResponse)
	err := c.cc.Invoke(ctx, "/NWPCDataService/FindDataPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NWPCDataServiceServer is the server API for NWPCDataService service.
type NWPCDataServiceServer interface {
	FindDataPath(context.Context, *DataRequest) (*DataPathResponse, error)
}

// UnimplementedNWPCDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNWPCDataServiceServer struct {
}

func (*UnimplementedNWPCDataServiceServer) FindDataPath(ctx context.Context, req *DataRequest) (*DataPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDataPath not implemented")
}

func RegisterNWPCDataServiceServer(s *grpc.Server, srv NWPCDataServiceServer) {
	s.RegisterService(&_NWPCDataService_serviceDesc, srv)
}

func _NWPCDataService_FindDataPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NWPCDataServiceServer).FindDataPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NWPCDataService/FindDataPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NWPCDataServiceServer).FindDataPath(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NWPCDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NWPCDataService",
	HandlerType: (*NWPCDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindDataPath",
			Handler:    _NWPCDataService_FindDataPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_service.proto",
}
