// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data_service.proto

package data_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_Unknown StatusCode = 0
	StatusCode_Success StatusCode = 1
	StatusCode_Failed  StatusCode = 2
)

var StatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Success",
	2: "Failed",
}

var StatusCode_value = map[string]int32{
	"Unknown": 0,
	"Success": 1,
	"Failed":  2,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{0}
}

type DataRequest struct {
	DataType             string   `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	StartTime            string   `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ForecastTime         string   `protobuf:"bytes,3,opt,name=forecast_time,json=forecastTime,proto3" json:"forecast_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{0}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *DataRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *DataRequest) GetForecastTime() string {
	if m != nil {
		return m.ForecastTime
	}
	return ""
}

type DataPathResponse struct {
	LocationType         string   `protobuf:"bytes,1,opt,name=location_type,json=locationType,proto3" json:"location_type,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataPathResponse) Reset()         { *m = DataPathResponse{} }
func (m *DataPathResponse) String() string { return proto.CompactTextString(m) }
func (*DataPathResponse) ProtoMessage()    {}
func (*DataPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{1}
}

func (m *DataPathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataPathResponse.Unmarshal(m, b)
}
func (m *DataPathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataPathResponse.Marshal(b, m, deterministic)
}
func (m *DataPathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPathResponse.Merge(m, src)
}
func (m *DataPathResponse) XXX_Size() int {
	return xxx_messageInfo_DataPathResponse.Size(m)
}
func (m *DataPathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataPathResponse proto.InternalMessageInfo

func (m *DataPathResponse) GetLocationType() string {
	if m != nil {
		return m.LocationType
	}
	return ""
}

func (m *DataPathResponse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type DataFileRequest struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataFileRequest) Reset()         { *m = DataFileRequest{} }
func (m *DataFileRequest) String() string { return proto.CompactTextString(m) }
func (*DataFileRequest) ProtoMessage()    {}
func (*DataFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{2}
}

func (m *DataFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataFileRequest.Unmarshal(m, b)
}
func (m *DataFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataFileRequest.Marshal(b, m, deterministic)
}
func (m *DataFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataFileRequest.Merge(m, src)
}
func (m *DataFileRequest) XXX_Size() int {
	return xxx_messageInfo_DataFileRequest.Size(m)
}
func (m *DataFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataFileRequest proto.InternalMessageInfo

func (m *DataFileRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type DataFileResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=StatusCode" json:"status,omitempty"`
	ErrorMessage         string     `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FilePath             string     `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize             int64      `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataFileResponse) Reset()         { *m = DataFileResponse{} }
func (m *DataFileResponse) String() string { return proto.CompactTextString(m) }
func (*DataFileResponse) ProtoMessage()    {}
func (*DataFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{3}
}

func (m *DataFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataFileResponse.Unmarshal(m, b)
}
func (m *DataFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataFileResponse.Marshal(b, m, deterministic)
}
func (m *DataFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataFileResponse.Merge(m, src)
}
func (m *DataFileResponse) XXX_Size() int {
	return xxx_messageInfo_DataFileResponse.Size(m)
}
func (m *DataFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataFileResponse proto.InternalMessageInfo

func (m *DataFileResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_Unknown
}

func (m *DataFileResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *DataFileResponse) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *DataFileResponse) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type FileContentRequest struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileContentRequest) Reset()         { *m = FileContentRequest{} }
func (m *FileContentRequest) String() string { return proto.CompactTextString(m) }
func (*FileContentRequest) ProtoMessage()    {}
func (*FileContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{4}
}

func (m *FileContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileContentRequest.Unmarshal(m, b)
}
func (m *FileContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileContentRequest.Marshal(b, m, deterministic)
}
func (m *FileContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileContentRequest.Merge(m, src)
}
func (m *FileContentRequest) XXX_Size() int {
	return xxx_messageInfo_FileContentRequest.Size(m)
}
func (m *FileContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileContentRequest proto.InternalMessageInfo

func (m *FileContentRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type FileContentResponse struct {
	ChunkLength          int64    `protobuf:"varint,3,opt,name=chunk_length,json=chunkLength,proto3" json:"chunk_length,omitempty"`
	Chunk                []byte   `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileContentResponse) Reset()         { *m = FileContentResponse{} }
func (m *FileContentResponse) String() string { return proto.CompactTextString(m) }
func (*FileContentResponse) ProtoMessage()    {}
func (*FileContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3385cd32ad6cfe64, []int{5}
}

func (m *FileContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileContentResponse.Unmarshal(m, b)
}
func (m *FileContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileContentResponse.Marshal(b, m, deterministic)
}
func (m *FileContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileContentResponse.Merge(m, src)
}
func (m *FileContentResponse) XXX_Size() int {
	return xxx_messageInfo_FileContentResponse.Size(m)
}
func (m *FileContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileContentResponse proto.InternalMessageInfo

func (m *FileContentResponse) GetChunkLength() int64 {
	if m != nil {
		return m.ChunkLength
	}
	return 0
}

func (m *FileContentResponse) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func init() {
	proto.RegisterEnum("StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*DataPathResponse)(nil), "DataPathResponse")
	proto.RegisterType((*DataFileRequest)(nil), "DataFileRequest")
	proto.RegisterType((*DataFileResponse)(nil), "DataFileResponse")
	proto.RegisterType((*FileContentRequest)(nil), "FileContentRequest")
	proto.RegisterType((*FileContentResponse)(nil), "FileContentResponse")
}

func init() { proto.RegisterFile("data_service.proto", fileDescriptor_3385cd32ad6cfe64) }

var fileDescriptor_3385cd32ad6cfe64 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x1b, 0x08, 0xcd, 0xc4, 0x10, 0xb3, 0xed, 0x21, 0x0a, 0x42, 0x2a, 0xcb, 0xa5, 0xe2,
	0xb0, 0xa2, 0xe1, 0xc2, 0x85, 0x53, 0xaa, 0x20, 0x24, 0xa8, 0x2a, 0xbb, 0x88, 0xa3, 0xb5, 0xd8,
	0x93, 0x66, 0x55, 0x67, 0xd7, 0x78, 0x27, 0x54, 0xed, 0x87, 0xf0, 0x37, 0xfc, 0x1b, 0xda, 0xb5,
	0x1d, 0x9c, 0xc0, 0xa1, 0xc7, 0xf7, 0x66, 0xc6, 0xef, 0xbd, 0x99, 0x35, 0xb0, 0x5c, 0x92, 0x4c,
	0x2d, 0x56, 0x3f, 0x55, 0x86, 0xa2, 0xac, 0x0c, 0x19, 0xae, 0x61, 0x74, 0x2e, 0x49, 0xc6, 0xf8,
	0x63, 0x83, 0x96, 0xd8, 0x0b, 0x18, 0xfa, 0x26, 0xba, 0x2b, 0x71, 0x12, 0x9c, 0x04, 0xa7, 0xc3,
	0xf8, 0xd0, 0x11, 0x57, 0x77, 0x25, 0xb2, 0x97, 0x00, 0x96, 0x64, 0x45, 0x29, 0xa9, 0x35, 0x4e,
	0x0e, 0x7c, 0x75, 0xe8, 0x99, 0x2b, 0xb5, 0x46, 0xf6, 0x1a, 0x9e, 0x2e, 0x4d, 0x85, 0x99, 0xb4,
	0x4d, 0x47, 0xdf, 0x77, 0x84, 0x2d, 0xe9, 0x9a, 0x78, 0x02, 0x91, 0xd3, 0xbb, 0x94, 0xb4, 0x8a,
	0xd1, 0x96, 0x46, 0x5b, 0x3f, 0x58, 0x98, 0x4c, 0x92, 0x32, 0xba, 0x2b, 0x1c, 0xb6, 0xa4, 0x17,
	0x9f, 0xc2, 0x61, 0x8b, 0x1b, 0xe9, 0x2d, 0xe6, 0x02, 0xc6, 0xee, 0xa3, 0x0b, 0x55, 0x60, 0x27,
	0xc8, 0x52, 0x15, 0x98, 0x96, 0x92, 0x56, 0x6d, 0x10, 0x47, 0x38, 0x61, 0xfe, 0x2b, 0xa8, 0x5d,
	0xd4, 0x03, 0x5b, 0x17, 0x03, 0x4b, 0x92, 0x36, 0xd6, 0xb7, 0x3f, 0x9b, 0x8d, 0x44, 0xe2, 0xe1,
	0xdc, 0xe4, 0x18, 0x37, 0x25, 0x67, 0x15, 0xab, 0xca, 0x54, 0xe9, 0x1a, 0xad, 0x95, 0xd7, 0xed,
	0x16, 0x42, 0x4f, 0x7e, 0xa9, 0xb9, 0x5d, 0xed, 0xfe, 0xae, 0xf6, 0xb6, 0x68, 0xd5, 0x3d, 0x4e,
	0x1e, 0x9d, 0x04, 0xa7, 0xfd, 0xba, 0x98, 0xa8, 0x7b, 0xe4, 0x67, 0xc0, 0x9c, 0xa7, 0xb9, 0xd1,
	0x84, 0x9a, 0x1e, 0x94, 0xe5, 0x02, 0x8e, 0x76, 0x46, 0x9a, 0x34, 0xaf, 0x20, 0xcc, 0x56, 0x1b,
	0x7d, 0x93, 0x16, 0xa8, 0xaf, 0x1b, 0x1b, 0xfd, 0x78, 0xe4, 0xb9, 0xcf, 0x9e, 0x62, 0xc7, 0xf0,
	0xd8, 0x43, 0xef, 0x22, 0x8c, 0x6b, 0xf0, 0x66, 0x06, 0xf0, 0x37, 0x37, 0x1b, 0xc1, 0x93, 0xaf,
	0xfa, 0x46, 0x9b, 0x5b, 0x1d, 0xf5, 0x1c, 0x48, 0x36, 0x59, 0x86, 0xd6, 0x46, 0x01, 0x03, 0x18,
	0x2c, 0xa4, 0x2a, 0x30, 0x8f, 0x0e, 0x66, 0xbf, 0x03, 0x18, 0x5f, 0x7c, 0xbb, 0x9c, 0xbb, 0x9d,
	0x26, 0xf5, 0xf3, 0x62, 0x67, 0x10, 0x2e, 0x94, 0xce, 0xdb, 0x63, 0xb3, 0x50, 0x74, 0xde, 0xd9,
	0xf4, 0xb9, 0xd8, 0x7f, 0x05, 0xbc, 0xc7, 0xde, 0xc3, 0xf8, 0x23, 0x52, 0x7b, 0x98, 0x4f, 0x7a,
	0x69, 0x58, 0x24, 0xf6, 0x0e, 0xdb, 0x4c, 0x76, 0x2f, 0xc7, 0x7b, 0xec, 0x03, 0x84, 0xe7, 0xe6,
	0x56, 0x17, 0x46, 0xe6, 0xae, 0xc2, 0x8e, 0xc4, 0xbf, 0x6b, 0x9c, 0x1e, 0x8b, 0xff, 0x2c, 0x8a,
	0xf7, 0xde, 0x06, 0xdf, 0x07, 0xfe, 0x5f, 0x78, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x02,
	0x9e, 0x48, 0x21, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NWPCDataServiceClient is the client API for NWPCDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NWPCDataServiceClient interface {
	FindDataPath(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataPathResponse, error)
	GetDataFileInfo(ctx context.Context, in *DataFileRequest, opts ...grpc.CallOption) (*DataFileResponse, error)
	DownloadFile(ctx context.Context, in *FileContentRequest, opts ...grpc.CallOption) (NWPCDataService_DownloadFileClient, error)
}

type nWPCDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewNWPCDataServiceClient(cc *grpc.ClientConn) NWPCDataServiceClient {
	return &nWPCDataServiceClient{cc}
}

func (c *nWPCDataServiceClient) FindDataPath(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataPathResponse, error) {
	out := new(DataPathResponse)
	err := c.cc.Invoke(ctx, "/NWPCDataService/FindDataPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nWPCDataServiceClient) GetDataFileInfo(ctx context.Context, in *DataFileRequest, opts ...grpc.CallOption) (*DataFileResponse, error) {
	out := new(DataFileResponse)
	err := c.cc.Invoke(ctx, "/NWPCDataService/GetDataFileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nWPCDataServiceClient) DownloadFile(ctx context.Context, in *FileContentRequest, opts ...grpc.CallOption) (NWPCDataService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NWPCDataService_serviceDesc.Streams[0], "/NWPCDataService/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &nWPCDataServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NWPCDataService_DownloadFileClient interface {
	Recv() (*FileContentResponse, error)
	grpc.ClientStream
}

type nWPCDataServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *nWPCDataServiceDownloadFileClient) Recv() (*FileContentResponse, error) {
	m := new(FileContentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NWPCDataServiceServer is the server API for NWPCDataService service.
type NWPCDataServiceServer interface {
	FindDataPath(context.Context, *DataRequest) (*DataPathResponse, error)
	GetDataFileInfo(context.Context, *DataFileRequest) (*DataFileResponse, error)
	DownloadFile(*FileContentRequest, NWPCDataService_DownloadFileServer) error
}

// UnimplementedNWPCDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNWPCDataServiceServer struct {
}

func (*UnimplementedNWPCDataServiceServer) FindDataPath(ctx context.Context, req *DataRequest) (*DataPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDataPath not implemented")
}
func (*UnimplementedNWPCDataServiceServer) GetDataFileInfo(ctx context.Context, req *DataFileRequest) (*DataFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataFileInfo not implemented")
}
func (*UnimplementedNWPCDataServiceServer) DownloadFile(req *FileContentRequest, srv NWPCDataService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}

func RegisterNWPCDataServiceServer(s *grpc.Server, srv NWPCDataServiceServer) {
	s.RegisterService(&_NWPCDataService_serviceDesc, srv)
}

func _NWPCDataService_FindDataPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NWPCDataServiceServer).FindDataPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NWPCDataService/FindDataPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NWPCDataServiceServer).FindDataPath(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NWPCDataService_GetDataFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NWPCDataServiceServer).GetDataFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NWPCDataService/GetDataFileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NWPCDataServiceServer).GetDataFileInfo(ctx, req.(*DataFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NWPCDataService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileContentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NWPCDataServiceServer).DownloadFile(m, &nWPCDataServiceDownloadFileServer{stream})
}

type NWPCDataService_DownloadFileServer interface {
	Send(*FileContentResponse) error
	grpc.ServerStream
}

type nWPCDataServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *nWPCDataServiceDownloadFileServer) Send(m *FileContentResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _NWPCDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NWPCDataService",
	HandlerType: (*NWPCDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindDataPath",
			Handler:    _NWPCDataService_FindDataPath_Handler,
		},
		{
			MethodName: "GetDataFileInfo",
			Handler:    _NWPCDataService_GetDataFileInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _NWPCDataService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data_service.proto",
}
